# Generated by Django 4.2.1 on 2023-09-29 09:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pokemons', '0008_remove_favouritepokemon_pokemon_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('move_id', models.IntegerField(unique=True)),
                ('move_name', models.CharField(max_length=200, unique=True)),
                ('move_type', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PokemonMoves',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('move_number', models.SmallIntegerField()),
                ('move', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon_moves.move')),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemons.pokemon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['move_number'],
            },
        ),
        migrations.AddConstraint(
            model_name='pokemonmoves',
            constraint=models.UniqueConstraint(fields=('pokemon', 'move_number'), name='4_moves', violation_error_message='There are already 4 moves assigned to this pokemon'),
        ),
    ]
